#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/string"
source "$UTILSH_PATH/src/shell/os"

##? Generates table of contents for markdown files inside
##?  local git repository
##?
##? using [DocToc](https://github.com/thlorenz/doctoc)
##?
#?? 1.0.0
##?
##? Usage:
##?    doctoc .
##?    doctoc <README.md>

docs::help "$@"

install_doctoc() {
  npm install -g doctoc
}

if ! [ -x "$(command -v doctoc)" ]; then
  sout::error "This command needs doctoc (https://github.com/thlorenz/doctoc) install first"
  if [[ $(sout::sure_question "Can you install it? (y/n)") != "Y" ]]; then
    exit 1
  fi

  install_doctoc
fi

doctoc "$@"
