#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/docs"

##? 😇 new_makefile: Generate the initial makefile in
##?  your project
##?
#?? 1.0.0
##?
##? Usage:
##?    new_makefile

docs::help "$@"

if [ -f Makefile ]; then
  sout::error "A makefile found! If you continue this file be removed"
  if [[ $(sout::sure_question "Do you want continue? (y/n)") != "Y" ]]; then
    exit 1
  fi
fi

cp "$UTILSH_PATH/templates/code/new_makefile/Makefile" .

sout::success Enjoy!
