#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/os"

source "$UTILSH_PATH/src/slack/slack_utils.sh"

##? 👻 Slack away status
##?
##? Set slack away status
##?
##? Using:
##?   away workspace_name
##?
##? 1.0.0
##?
##? Usage:
##?    away <workspace_name>

docs::help "$@"

if [ -z "$1" ]; then
  sout::error "Need a workspace name"
  exit 1
fi

WORKSPACE=$1

slack::focus_workspace "$WORKSPACE"
slack::open_channel "me"
slack::set_away
