#!/usr/bin/env bash

set -eu

function error() {
  echo "🚨 Error: $1"
  exit 1
}

function change_version() {
  local current_version="0.0.0"
  if [[ -f version ]]; then
    current_version=$(cat version)
  fi
  IFS=. read -r major minor patch <<<"$current_version"

  case "$VERSION_PARAM" in
  "PATCH")
    ((patch++))
    ;;
  "MINOR")
    patch=0
    ((minor++))
    ;;
  "MAJOR")
    minor=0
    patch=0
    ((major++))
    ;;
  *)
    error "Invalid INCREASE word use: 'major' | 'minor' | 'patch'"
    exit 1
    ;;
  esac

  local new_version="$major"."$minor"."$patch"
  echo "$new_version" >version
  git commit -am "Close version" 2>/dev/null
}

if [[ $# != 1 ]]; then
  error "Please specify the version to release patch | minor | major"
fi

VERSION_PARAM=$(echo "$1" | tr [a-z] [A-Z])
BRANCH=$(git rev-parse --abbrev-ref HEAD)

function verify_master_branch() {
  if [[ ${BRANCH} != 'master' ]]; then
    error "Invalid branch name ${BRANCH}"
  fi
}

function verify_uncommitted_changes() {
  if [[ $(git status --porcelain) ]]; then
    error "There are uncommitted changes in the working tree."
  fi
}

function publish() {
  local new_version=$(cat version)
  git tag "v$new_version" -m "$new_version"
  git push origin --tags
}

verify_uncommitted_changes
verify_master_branch
change_version
make check
publish
echo "📦✅"
