#!/usr/bin/env bash

set -euo pipefail

echo "🚀 Installing utilsh"
echo
read -rp "🤔 Where do you want to install me? (default ~/.utilsh): " UTILSH_PATH
echo
UTILSH_PATH=${UTILSH_PATH:-"$HOME/.utilsh"}
echo "👉  Cloning into: '$UTILSH_PATH'"
git clone --depth 1 git@github.com:raulanatol/utilsh.git "$UTILSH_PATH"
echo
echo "👌 Remember create the environment variable and restart the shell"
echo "UTILSH_PATH=$UTILSH_PATH"
echo "and export the bin path"
echo "PATH=PATH:$UTILSH_PATH/bin"
