#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/docs"

##? Add all files and then a commit
#?? 1.0.0
##?
##? Usage:
##?    commit            # A prompt appears asking for the commit message
##?    commit <message>

docs::help "$@"

git add -A

if [ -z "$1" ]; then
  git commit -S
else
  git commit -S -m"$*"
fi
