#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/sout"

##? Delete all branches that have been merged in remote
#?? 1.0.0
##?
##? Usage:
##?    delete-merged

docs::help "$@"

git branch --merged | egrep -v "(^\*|master|develop|main)" | xargs git branch -d

sout::info "🧹 cleanup done!"
