#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/git"
source "$UTILSH_PATH/src/shell/string"
source "$UTILSH_PATH/src/shell/sout"

##? Fix the current branch and create a Pull Request
#?? 1.0.0
##?
##? Usage:
##?    fix

docs::help "$@"

if ! (git::is_in_repo); then
  sout::error "Not in a git repository"
  exit 1
fi

if ! (git::has_remote); then
  sout::error "Not remote found"
  exit 1
fi

current_branch=$(git::current_branch)
issue_number=${current_branch#*_}

if ! (string::is_a_number "$issue_number"); then
  log::error "This is not a valid branch name ${current_branch}"
  exit 1
fi

git add -A
git diff-index --quiet HEAD || git commit -m "Fix #${issue_number}"
git push -u origin "$(git rev-parse --abbrev-ref HEAD)"

remote_url=$(git::get_remote_https_url)
open "${remote_url}pull/new/${current_branch}"
log::success "🤘 Done!"
