#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/os"

##? 🕴 Git Branches Helper
##?
##?  using [git-jump](https://github.com/mykolaharmash/git-jump)
##?
#?? 1.0.0
##?
##? Usage:
##?    jump

docs::help "$@"

install_git_jump() {
  if os::is_macos; then
    brew tap mykolaharmash/git-jump
    brew install git-jump
  fi
}

git jump -l
if ! [ $? -eq 0 ]; then
  sout::error "This command needs git-jump (https://github.com/mykolaharmash/git-jump) install first"
  if [[ $(sout::sure_question "Can you install it? (y/n)") != "Y" ]]; then
    exit 1
  fi

  install_git_jump
fi

git jump "$@"
