#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/os"

##? 🐳 Top-like interface for container metrics
##?
##? ctop provides a concise and condensed overview
##? of real-time metrics for multiple containers.
##?
##? Using: https://github.com/bcicen/ctop
##?
#?? 1.0.0
##?
##? Usage:
##?    ctop

docs::help "$@"

install_ctop() {
  if os::is_macos; then
    brew install ctop
  fi
}

if ! [ -x "$(command -v ctop)" ]; then
  sout::error "This command needs ctop (https://github.com/bcicen/ctop) install first"
  if [[ $(sout::sure_question "Can you install it? (y/n)") != "Y" ]]; then
    exit 1
  fi

  install_ctop
fi

ctop
