#!/usr/bin/env bash

set -euo pipefail

source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/sout"

##? ♻️️ Update utilsh
##?
#?? 1.0.0
##?
##? Usage:
##?    update

docs::help "$@"

sout::info " ♻️️  Updating utilsh"
cd "$UTILSH_PATH"
git checkout main
git pull

sout::info " 👌 Done!"
