#!/usr/bin/env bash

set -euo pipefail

source "$UTILSH_PATH/src/shell/docs"

##? ♻️️ Update utilsh
##?
#?? 1.0.0
##?
##? Usage:
##?    update

docs::help "$@"

echo "♻️️ Updating utilsh"
cd "$UTILSH_PATH"
git checkout master
git pull
echo "👌 Done!"
