#!/usr/bin/env bash

set -euo pipefail

source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/sout"

##? ♻️️ Update utilsh
##?
#?? 1.0.0
##?
##? Usage:
##?    update

docs::help "$@"

update_dotfiles() {
  if [[ -n "${DOTFILES_PATH}" ]]; then
    "$DOTFILES_PATH"/bin/update
  fi
}

sout::info " ♻️️  Updating utilsh"
cd "$UTILSH_PATH"
git checkout master
git pull

update_dotfiles

sout::info " 👌 Done!"
