#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/string"
source "$UTILSH_PATH/src/shell/docs"

docs::help "$@"

ACTION=$(string::to_uppercase "$1")

if [[ $ACTION == SHOW ]]; then
  defaults write com.apple.finder AppleShowAllFiles YES
  sout::info "🙊 show hidden files"
else
  defaults write com.apple.finder AppleShowAllFiles NO
  sout::info "🙈 hide hidden files"
fi

killall Finder
