#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/string"
source "$UTILSH_PATH/src/shell/docs"

##? 📶 wifi:
##?   * On/Off Wifi
##?   * dhcp: Renew DHCP Lease
##?   * password: Get password of the current wifi
#?? 1.0.0
##?
##? Usage:
##?
##?    wifi <on>
##?    wifi <off>
##?    wifi <dhcp>
##?    wifi <password>

docs::help "$@"

ACTION=$(string::to_lowercase "$1")
DEVICE=${2:-en0}

case "$ACTION" in
"off" | "on")
  networksetup -setairportpower "$DEVICE" "$ACTION"
  ;;
"dhcp")
  sudo ipconfig set "$DEVICE" DHCP
  ;;
"password")
  ssid="$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk '/ SSID/ {print substr($0, index($0, $2))}')"
  security find-generic-password -D "AirPort network password" -a "$ssid" -gw
  ;;
*)
  sout::error "Invalid action $ACTION"
  ;;
esac
