#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/string"
source "$UTILSH_PATH/src/shell/docs"

##? 📟 zoom:
##?   * start: Start personal meeting
#?? 1.0.0
##?
##? Usage:
##?
##?    zoom <start>

docs::help "$@"

start_meeting() {
  osascript <<EOF
    on run argv
      tell application "zoom.us" to activate

      tell application "System Events"
        tell process "zoom.us"

          set StartMeeting to menu item "Start Meeting" of menu "zoom.us" of menu bar 0

          repeat while not enabled of StartMeeting
            delay 0.25
          end repeat

          click StartMeeting

        end tell
      end tell
      return ""
    end run
EOF
}

ACTION=$(string::to_lowercase "$1")

case "$ACTION" in
  "start")
    start_meeting
    ;;
  *)
    sout::error "Invalid action $ACTION"
    ;;
esac
