#!/usr/bin/env bash

set -eo pipefail

source "$RAUTILS_PATH/src/shell/cout"
source "$RAUTILS_PATH/src/shell/assert"

assert::rautils_env_exist
assert::env_exist GITHUB_TOKEN
assert::arguments_more_than 3 $#

REPOSITORY_OWNER=$1
REPOSITORY_NAME=$2
EVENT_TYPE=$3
DISPATCH_EXTRA_DATA="${@:4}"

DATA="{ \"event_type\": \""$EVENT_TYPE"\""

if [[ -n ${DISPATCH_EXTRA_DATA} ]]; then
  DATA="$DATA, \"client_payload\": "${DISPATCH_EXTRA_DATA}""
fi

DATA="$DATA }"

assert::is_valid_json "$DATA"

curl -H "Accept: application/vnd.github.everest-preview+json" \
  -H "Authorization: token ${GITHUB_TOKEN}" \
  --request POST \
  --data "$DATA" \
  "https://api.github.com/repos/${REPOSITORY_OWNER}/${REPOSITORY_NAME}/dispatches"
