#!/usr/bin/env bash

set -eu

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/assert"
source "$UTILSH_PATH/src/shell/development"

assert::total_arguments $# 1 "Please specify the version increase: minor | major | patch"
assert::git::not::has_changes
assert::git::on_master

BRANCH=$(git::current_branch)
CURRENT_VERSION=$(cat version)
NEW_VERSION=$(development::increase_semversion "$CURRENT_VERSION" "$1")

change_version() {
  echo "$NEW_VERSION" >version
}

create_tag() {
  git commit -am "Close version $NEW_VERSION"
  git tag "v$NEW_VERSION" -m "$NEW_VERSION"
  git push origin --tags
}

change_version "$1"
create_tag
