#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/os"

##? 🖼 Change irvue wallpaper
##?
##? Change the current wallpaper using Irvue app
##?
##? Using:
##?   irvue change
##?
##? 1.0.0
##?
##? Usage:
##?    change

docs::help "$@"

osascript <<EOF
  tell application "Irvue"
    change current wallpaper
  end tell
EOF
