#!/usr/bin/env bash

assert::env_exist() {
  result=$(env | awk -F '=' "/$1/ {print \$1}" | grep -c -E -i "^$1\$")
  if [[ ! $result -eq 1 ]]; then
    sout::error " Need to define $1 first"
    exit 1
  fi
}

assert::rautils_env_exist() {
  assert::env_exist RAUTILS_PATH
}

assert::total_arguments() {
  if [[ "$1" -ne "$2" ]]; then
    sout::error " Waiting for $2 parameters"
    exit 1
  fi
}

assert::arguments_more_than() {
  if [[ $1 -gt $2 ]]; then
    sout::error " Need at least $1 parameters"
    exit 1
  fi
}

assert::is_valid_json() {
  if ! jq -e . >/dev/null 2>&1 <<<"$1"; then
    sout::error " Invalid JSON format: $1"
    exit 1
  fi
}
