#!/usr/bin/env bash

extract_help() {
  local -r file="$1"
  grep "^##?" "$file" | cut -c 5-
}

extract_version() {
  local -r file="$1"
  grep "^#??" "$file" | cut -c 5-
}

docs::help() {
  local -r file="$0"

  case "${!#:-}" in
  -h | --help)
    extract_help "$file"
    exit 0
    ;;
  -v | --version)
    extract_version "$file"
    exit 0
    ;;
  esac
}