#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/string"
source "$UTILSH_PATH/src/shell/docs"

docs::help "$@"

##? Evaluate the zsh starting time.

for i in $(seq 1 10); do
  /usr/bin/time /bin/zsh -i -c exit
done
