#!/usr/bin/env bash

string::to_uppercase() {
  echo "$@" | tr [a-z] [A-Z]
}

string::to_lowercase() {
  echo "$@" | tr [A-Z] [a-z]
}

string::is_a_number() {
  re='^[0-9]+$'
  if ! [[ $1 =~ $re ]]; then
    echo "error: Not a number '$1'" >&2
    return 2
  fi
  return 0
}