#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/docs"

##? 📂 Calculate the current folder size
##?   (using du or ncdu)
##?
##? -c to enable ncdu with color mode
#?? 1.0.0
##?
##? Usage:
##?    folder_size
##?    folder_size -c

docs::help "$@"

if [[ $1 == '-c' ]]; then
  ncdu --color dark -rr -x
else
  du -sh .
fi
