#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/string"
source "$UTILSH_PATH/src/shell/os"

##? 🏹 fetch: Http request using httpie (https://httpie.org/)
##?
##?   using [httpie](https://httpie.org/)
##?
#?? 1.0.0
##?
##? Usage:
##?    fetch
##?    fetch GET <url>
##?    fetch POST <url> <json_data>
##?    fetch PUT <url> <json_data>
##?    fetch HELP

docs::help "$@"

install_httpie() {
  if os::is_macos; then
    brew install httpie
  fi
}

if ! [ -x "$(command -v http)" ]; then
  sout::error "This command needs httpie (https://httpie.org/) install first"
  if [[ $(sout::sure_question "Can you install it? (y/n)") != "Y" ]]; then
    exit 1
  fi

  install_httpie
fi

METHOD=$(string::to_uppercase "$1")
URL=$2
case $METHOD in
  POST | PUT | GET | DELETE)
    shift 2
    http -j "$METHOD" "$URL" "$@"
    ;;
  HELP)
    open "https://httpie.org/docs"
    ;;
  *)
    sout::error "Invalid method ${METHOD}"
    exit 1
    ;;
esac
