#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/string"
source "$UTILSH_PATH/src/shell/docs"

##? 📡 ip: Get the local (-l) or public ip
##?
##?   -l Local IP
##?
#?? 1.0.0
##?
##? Usage:
##?    ip
##?    ip -l

docs::help "$@"

LOCAL_OR_PUBLIC=$(string::to_uppercase "$1")
DEVICE=${2:-en0}

if [[ $LOCAL_OR_PUBLIC != '-L' ]]; then
  sout::info "📡 public: $(dig +short myip.opendns.com @resolver1.opendns.com)"
else
  sout::info "📡 local: $(ipconfig getifaddr "$DEVICE")"
fi
