#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/docs"

##? 🐌 speed: Internet connection speed test
##?
##?   using [fast-cli](https://github.com/sindresorhus/fast-cli)
##?
#?? 1.0.0
##?
##? Usage:
##?    speed

docs::help "$@"

if ! [ -x "$(command -v fast)" ]; then
  sout::error "This command needs fast (https://github.com/sindresorhus/fast-cli) install first"
  sout::info "npm install -g fast-cli"
  exit 1
fi

fast --upload
