#!/usr/bin/env bash

set -eo pipefail

source "$UTILSH_PATH/src/shell/sout"
source "$UTILSH_PATH/src/shell/docs"
source "$UTILSH_PATH/src/shell/os"

##? 🧪 usage: Monitoring the current network utilization by process,
##?    connection and remote IP/hostname
##?
##? using [bandwhich](https://github.com/imsnif/bandwhich)
##?
#?? 1.0.0
##?
##? Usage:
##?    usage

docs::help "$@"

install_bandwhich() {
  if os::is_macos; then
    brew install bandwhich
  fi
}

if ! [ -x "$(command -v bandwhich)" ]; then
  sout::error "This command needs bandwich (https://github.com/imsnif/bandwhich) install first"
  if [[ $(sout::sure_question "Can you install it? (y/n)") != "Y" ]]; then
    exit 1
  fi

  install_bandwhich
fi

sudo bandwhich "$@"
